package com.erp.manufacturing.security;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class SchemaMigrationRunner implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        ensureTable("APP_USER_PERMISSION", "CREATE TABLE app_user_permission (user_id NUMBER NOT NULL, permission_code VARCHAR2(100) NOT NULL, CONSTRAINT pk_app_user_permission PRIMARY KEY (user_id, permission_code), CONSTRAINT fk_app_user_permission_user FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE)");
        if (tableExists("APP_USER_PERMISSION")) seedBootstrapAdministratorPermissions();

        ensureTable("NOTIFICATION", "CREATE TABLE notification (notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recipient_email VARCHAR2(100), subject VARCHAR2(150) NOT NULL, message VARCHAR2(1000) NOT NULL, status VARCHAR2(30) NOT NULL, source_type VARCHAR2(50), source_id NUMBER, created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, sent_date TIMESTAMP)");
        ensureIndex("IX_NOTIFICATION_SOURCE", "CREATE INDEX ix_notification_source ON notification(source_type, source_id)");
        ensureIndex("IX_NOTIFICATION_STATUS", "CREATE INDEX ix_notification_status ON notification(status)");

        ensureTable("GENERALLEDGERENTRY", "CREATE TABLE generalledgerentry (ledger_entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_code VARCHAR2(30) NOT NULL, account_name VARCHAR2(100) NOT NULL, debit_amount NUMBER(12,2) DEFAULT 0 NOT NULL, credit_amount NUMBER(12,2) DEFAULT 0 NOT NULL, entry_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, source_table VARCHAR2(100), source_id NUMBER, description VARCHAR2(255), CONSTRAINT ck_gl_debit_credit_nonnegative CHECK (debit_amount >= 0 AND credit_amount >= 0), CONSTRAINT ck_gl_one_side CHECK ((debit_amount > 0 AND credit_amount = 0) OR (debit_amount = 0 AND credit_amount > 0)))");
        ensureIndex("IX_GL_SOURCE", "CREATE INDEX ix_gl_source ON generalledgerentry(source_table, source_id)");
        ensureIndex("IX_GL_ACCOUNT", "CREATE INDEX ix_gl_account ON generalledgerentry(account_code)");
        ensureIndex("IX_GL_ENTRY_DATE", "CREATE INDEX ix_gl_entry_date ON generalledgerentry(entry_date)");
    }

    private void ensureTable(String tableName, String ddl) {
        if (tableExists(tableName)) {
            log.info("Table {} already exists.", tableName);
            return;
        }
        log.info("Creating table {}...", tableName);
        try {
            jdbcTemplate.execute(ddl);
        } catch (Exception exception) {
            log.error("Failed to create table {}: {}", tableName, exception.getMessage());
        }
    }

    private void ensureIndex(String indexName, String ddl) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_indexes WHERE index_name = ?",
                Integer.class,
                indexName
        );
        if (count != null && count > 0) return;
        try {
            jdbcTemplate.execute(ddl);
        } catch (Exception exception) {
            log.error("Failed to create index {}: {}", indexName, exception.getMessage());
        }
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_tables WHERE table_name = ?",
                Integer.class,
                tableName
        );
        return count != null && count > 0;
    }

    private void seedBootstrapAdministratorPermissions() {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM app_user_permission", Integer.class);
        if (count != null && count > 0) return;
        log.info("Assigning full module permissions to existing bootstrap administrators...");
        PermissionCatalog.MODULE_ACTIONS.forEach((module, actions) -> actions.forEach(action ->
                jdbcTemplate.update("INSERT INTO app_user_permission (user_id, permission_code) SELECT user_id, ? FROM app_user WHERE role = 'ADMIN'", module + ":" + action)
        ));
    }
}
