-- Manual schema changes required because spring.jpa.hibernate.ddl-auto=none.
-- Run as the application schema owner before deploying the production-readiness changes.

ALTER TABLE purchaseorder ADD version NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE salesorder ADD version NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE productionorder ADD version NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE payment ADD version NUMBER DEFAULT 0 NOT NULL;

CREATE TABLE inventorybalance (
    inventory_balance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    quantity_on_hand NUMBER(12,2) DEFAULT 0 NOT NULL,
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT uk_inventory_balance_item_wh UNIQUE (item_id, warehouse_id),
    CONSTRAINT fk_inventory_balance_item
        FOREIGN KEY (item_id)
        REFERENCES item(item_id),
    CONSTRAINT fk_inventory_balance_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouse(warehouse_id),
    CONSTRAINT ck_inventory_balance_qty
        CHECK (quantity_on_hand >= 0)
);

CREATE INDEX ix_inventory_balance_item ON inventorybalance(item_id);
CREATE INDEX ix_inventory_balance_warehouse ON inventorybalance(warehouse_id);

CREATE TABLE systemconfiguration (
    config_key VARCHAR2(100) PRIMARY KEY,
    config_value VARCHAR2(255) NOT NULL,
    description VARCHAR2(255)
);

INSERT INTO systemconfiguration (config_key, config_value, description)
VALUES (
    'purchase.approval.threshold',
    '100000',
    'Purchase orders above this total require manager approval'
);

-- Optional one-time seed if existing item.current_stock should start in a default warehouse.
-- Replace :default_warehouse_id before running, or skip this if balances should start empty.
--
-- INSERT INTO inventorybalance (item_id, warehouse_id, quantity_on_hand)
-- SELECT item_id, :default_warehouse_id, COALESCE(current_stock, 0)
-- FROM item
-- WHERE COALESCE(current_stock, 0) > 0;
