-- Manual schema changes required because spring.jpa.hibernate.ddl-auto=none.
-- Run as the application schema owner before starting the application.

ALTER TABLE item ADD version NUMBER DEFAULT 0 NOT NULL;

CREATE TABLE app_user (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(30) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    employee_id NUMBER,
    CONSTRAINT fk_app_user_employee
        FOREIGN KEY (employee_id)
        REFERENCES employee(employee_id)
);

-- Replace the password hash before using this account in production.
-- This BCrypt hash is for: admin123
INSERT INTO app_user (username, password_hash, role, enabled, employee_id)
VALUES (
    'admin',
    '$2a$10$Dow1Pq89zrTBbHLqk7N7He5GCIXTyHvyKDN1ahPK6PaBZcR2DXnoG',
    'ADMIN',
    1,
    NULL
);
